services:
  frontend:
    build: 
      context: ./app
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
      - /app/node_modules
    command: sh -c "npx http-server . -p \$${PORT:-8080} -c-1"

  servidor:
    build:
      context: ./servidor
    ports:
      - "8000:3000"
    environment:
      DB_HOST: "bdd"
      DB_PORT: "5432"
      DB_USER: "usuario"
      DB_PASS: "contraseña"
      DB_NAME: "bdd"
    depends_on:
      - bdd

  bdd:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: "usuario"
      POSTGRES_PASSWORD: "contraseña"
      POSTGRES_DB: "bdd"
    volumes:
      - ./data:/var/lib/postgresql
      - ./01_esquema_bdd.sql:/docker-entrypoint-initdb.d/01_esquema_bdd.sql:ro
      - ./02_seeds.sql:/docker-entrypoint-initdb.d/02_seeds.sql:ro
  seed:
    image: postgres:18-alpine
    depends_on:
      - bdd
    volumes:
      - ./02_seeds.sql:/seeds/02_seeds.sql:ro
    environment:
      PGPASSWORD: "contraseña"
    command: >
      sh -c "sleep 3 &&
      psql -h bdd -U usuario -d bdd -f /seeds/02_seeds.sql"